### ISSUE TITLE
About the consumption of memory when training

### ISSUE THREAD

**Issue by KevinWisbay** [Strawberry-Eat-Mango/PCT_Pytorch#27]
I got this when training modelnet40 dataset;
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 3.94 GiB total capacity; 2.98 GiB already allocated; 14.25 MiB free; 3.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

And it dosent work, even if I reduce the batchsize(2). 
Can I have any other options, besides a new GPU with more memory? How much memory do you use when training?
Thanks a lot!

**Comment by 294coder** [comment]
收到
